plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.navigationmodule'
version = '0.1.0'

android {
  namespace "expo.modules.navigationmodule"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
  }
  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation "com.mapbox.navigationcore:android-ndk27:3.27.3"
  implementation "com.mapbox.navigationcore:ui-components-ndk27:3.27.3"
  implementation "androidx.constraintlayout:constraintlayout:2.2.1"
  implementation "androidx.appcompat:appcompat:1.7.0"
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1"
}
